name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build-container:
    uses: ./.github/workflows/build-container.yml

  pre-commit:
    needs: build-container
    runs-on: ubuntu-latest
    container: ${{ needs.build-container.outputs.image }}
    steps:
    - uses: actions/checkout@v4

    - name: Run pre-commit
      run: pre-commit run --all-files
